---
stages:
  - build
  - test

build:
  tags:
    - docker
  stage: build
  image: registry.esss.lu.se/gabrielfedel/docker-e3:next
  script:
    # base 3.15.6 req 3.1.0
    - make vars
    - make init
    - make build
    - make install
    # base 3.15.6 req 3.1.2
    - sed -i 's/3.1.0/3.1.2/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install
    # base 7.0.3 req 3.1.2
    - sed -i 's/base-3.15.6/base-7.0.3/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install
    # base 7.0.3 req 3.1.0
    - sed -i 's/3.1.2/3.1.0/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install

test:
  tags:
    - docker
  stage: test
  image: registry.esss.lu.se/gabrielfedel/docker-e3-test:next
  before_script:
    - yum -y install psmisc
  script:
    # base 3.15.6 req 3.1.0
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-3.15.6/require/3.1.0/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    # base 3.15.6 req 3.1.2
    - sed -i 's/3.1.0/3.1.2/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-3.15.6/require/3.1.2/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    # base 7.0.3 req 3.1.2
    - sed -i 's/base-3.15.6/base-7.0.3/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-7.0.3/require/3.1.2/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    # base 7.0.3 req 3.1.0
    - sed -i 's/3.1.2/3.1.0/g' configure/RELEASE
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-7.0.3/require/3.1.0/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
