---
stages:
  - build
  - test

build:
  tags:
    - docker
  stage: build
  image: registry.esss.lu.se/gabrielfedel/docker-e3:next
  script:
    - yes | /root/e3/e3_building_config.bash -b 3.15.6 -r 3.1.0 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - yes | /root/e3/e3_building_config.bash -b 3.15.6 -r 3.1.2 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - killall procServ
    - yes | /root/e3/e3_building_config.bash -b 7.0.3 -r 3.1.0 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - yes | /root/e3/e3_building_config.bash -b 7.0.3 -r 3.1.2 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install

test:
  tags:
    - docker
  stage: test
  image: registry.esss.lu.se/gabrielfedel/docker-e3-test:next
  before_script:
    - yum -y install psmisc
  script:
    - yes | /root/e3/e3_building_config.bash -b 3.15.6 -r 3.1.0 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-3.15.6/require/3.1.0/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    - yes | /root/e3/e3_building_config.bash -b 3.15.6 -r 3.1.2 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-3.15.6/require/3.1.2/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    - yes | /root/e3/e3_building_config.bash -b 7.0.3 -r 3.1.0 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-7.0.3/require/3.1.0/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
    - yes | /root/e3/e3_building_config.bash -b 7.0.3 -r 3.1.2 setup > /dev/null
    - make vars
    - make init
    - make build
    - make install
    - procServ -P 2000 /epics/base-7.0.3/require/3.1.2/bin/iocsh.bash cmds/start.cmd
    - pytest --pref=TEST:A scaling/tests
    - killall procServ
